# Generated by Django 4.0.6 on 2022-07-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='e_commerce__last_na_33fb2a_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='e_commerce_customers',
        ),
    ]
