# Generated by Django 4.0.6 on 2022-07-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='e_commerce_customer',
        ),
    ]
