# Generated by Django 4.0.6 on 2022-07-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgecenter', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', "Don't want to Say")], default='M', max_length=1)),
                ('state', models.CharField(max_length=255)),
                ('lga', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('contact_address', models.TextField()),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('identification', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True)),
                ('program_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgecenter.state')),
            ],
        ),
    ]
