# Generated by Django 4.0.6 on 2022-07-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgecenter', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='ProgramState',
        ),
    ]
