# Generated by Django 4.0.6 on 2022-07-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgecenter', '0004_rename_state_programstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='program_state',
            new_name='programstate',
        ),
    ]
