# Generated by Django 4.0.6 on 2022-07-16 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgecenter', '0005_rename_program_state_student_programstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
