# Generated by Django 4.0.6 on 2022-07-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgecenter', '0007_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='knowledgecenter.programme'),
            preserve_default=False,
        ),
    ]
