# Generated by Django 4.0.6 on 2022-07-24 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgecenter', '0010_module_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
