# Generated by Django 4.0.6 on 2022-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgecenter', '0012_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='programme',
            field=models.ManyToManyField(to='knowledgecenter.programme'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='programstate',
            field=models.ManyToManyField(to='knowledgecenter.programstate'),
        ),
    ]
